/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	INIT("[Action][START][Entity][GAME]",1500),
    GO_BACK("[Action][GO_BACK]", 1500),
    SOUND_OFF("[Action][SOUND_MANIPULATION_OFF]", 1500),
    SOUND_ON("[Action][SOUND_MANIPULATION_ON]", 1500),
    ROQUE("[Action][SPECIAL][SpecialMove][ROQUE]", 1500),
    END("[Action][END]", 1500);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
